=== marcoaurora/test1/TestTemplate/SOA/Schemas/Test.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.example.org"
            targetNamespace="http://www.example.org" elementFormDefault="qualified">
  <xsd:element name="TabulatoCasconf">
    <xsd:complexType>
       <xsd:sequence>
           <xsd:element name="Intestazione" type="xsd:string"/>
           <xsd:element name="ListConfezioni" type="ListConfezioniType"/>
           <xsd:element name="ListSuperConfezioni" type="ListConfezioniType"/>
       </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:complexType name="ConfezioneType">
       <xsd:sequence>
           <xsd:element name="SSCC" type="xsd:string"/>
           <xsd:element name="Taglio" type="xsd:string"/>
           <xsd:element name="Quantita" type="xsd:string"/>
       </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ListConfezioniType">
       <xsd:sequence>
           <xsd:element name="Confezione" type="ConfezioneType" minOccurs="0" maxOccurs="unbounded"/>
       </xsd:sequence>
    </xsd:complexType>
  
  <xsd:element name="Tabulato">
    <xsd:complexType>
       <xsd:sequence>
           <xsd:element name="Intestazione" type="xsd:string"/>
           <xsd:element name="Riga" type="RigaType" minOccurs="0" maxOccurs="unbounded"/>
       </xsd:sequence>
    </xsd:complexType>
   </xsd:element>  

 <xsd:complexType name="RigaType">
       <xsd:sequence>
           <xsd:element name="ansiCC" type="xsd:string"/>
           <xsd:element name="testo" type="xsd:string"/>
       </xsd:sequence>
    </xsd:complexType>  
   
   
   <xsd:element name="TrasferisciInPresenzaInput">
    <xsd:complexType>
       <xsd:sequence>
           <xsd:element name="Intestazione" type="xsd:string"/>
           <xsd:element name="Confezione" type="ConfezioneType" minOccurs="0" maxOccurs="unbounded"/>
           <xsd:element name="SuperConfezione" type="ConfezioneType" minOccurs="0" maxOccurs="unbounded"/>
       </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
</xsd:schema>

=== marcoaurora/test1/TestTemplate/SOA/Transformations/XSLNonDeployedFiles/TestTemplate-Target.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<ns1:Tabulato xmlns:ns1="http://www.example.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org file:/media/sf_D_DRIVE/Clienti/BDI/Progetti/Tracciamento/Casconf/TestTemplate/SOA/Schemas/Test.xsd">
   <ns1:Intestazione>Intestazione20</ns1:Intestazione>
   <ns1:Riga>
      <ns1:ansiCC>0</ns1:ansiCC>
      <ns1:testo>ELENCO CONFEZIONI TRASFERITE</ns1:testo>
   </ns1:Riga>
   <ns1:Riga>
      <ns1:ansiCC/>
      <ns1:testo>SSCC: SSCC78 Taglio: Taglio79 Quantita: Quantita80</ns1:testo>
   </ns1:Riga>
   <ns1:Riga>
      <ns1:ansiCC/>
      <ns1:testo>SSCC: SSCC81 Taglio: Taglio82 Quantita: Quantita83</ns1:testo>
   </ns1:Riga>
   <ns1:Riga>
      <ns1:ansiCC/>
      <ns1:testo>SSCC: SSCC84 Taglio: Taglio85 Quantita: Quantita86</ns1:testo>
   </ns1:Riga>
</ns1:Tabulato>
